Session status tracking
stanfordnmbl/opencap-api pull request #156
Opened 2024-01-23 14:55 UTC by olehkorkh-planeks

2024-02-08 18:40 UTC, suhlrich requested changes
Looks good. One change requested.

2024-02-16 09:07 UTC, olehkorkh-planeks commented on mcserver/views.py
> +                    filter_kwargs['user'] = request.user
@suhlrich I added the commit. Now an optional argument `username` is supported.
https://github.com/stanfordnmbl/opencap-api/pull/156/commits/9a3ca4d6f7f4650ff187778ad7fbfb6daa612b8d

2024-04-05 05:52 UTC, suhlrich approved these changes

2024-04-05 05:52 UTC, merged

2024-04-05 05:56 UTC, suhlrich commented
Do we need to migrate now? @antoinefalisse

2024-04-05 18:49 UTC, antoinefalisse commented
there is a bunch of stuff in dev, will do soon