dev: reduce processed fields clutter in list view
stanfordnmbl/opencap-api pull request #223
Opened 2024-10-01 17:44 UTC by carmichaelong

shorten some column names and clean up duration formatting

2024-10-01 22:07 UTC, AlbertoCasasOrtiz requested changes
I added a comment with the error the API is throwing locally.

2024-10-01 22:07 UTC, AlbertoCasasOrtiz commented on mcserver/admin.py
> +    formatted_duration.short_description = 'duration'
I tried to run it locally and it is complaining about `formated_duration `and `processed_duration` not being defined:

```
  File "C:\Workspaces\opencap\opencap-api\mcserver\admin.py", line 97, in <module>
    class TrialAdmin(admin.ModelAdmin):
  File "C:\Workspaces\opencap\opencap-api\mcserver\admin.py", line 112, in TrialAdmin
    formatted_duration.short_description = 'duration'
NameError: name 'formatted_duration' is not defined
```

2024-10-01 23:49 UTC, carmichaelong commented
@AlbertoCasasOrtiz thanks for the catch (i should set up a local build at some point). pushed a commit that should fix the issue

2024-10-02 18:15 UTC, AlbertoCasasOrtiz commented
It fixed it! I got then the same problem with processed_count and added a function too so it recognizes it.

Now, when I go to admin console, I got this:

```
   File "C:\Workspaces\opencap\opencap-api\mcserver\admin.py", line 117, in formatted_duration
     hours, remainder = divmod(int(obj.duration.total_seconds()), 3600)
 AttributeError: 'Trial' object has no attribute 'duration'
 [02/Oct/2024 11:13:48] "GET /admin/mcserver/trial/ HTTP/1.1" 500 452129
```

Looks like the `obj.duration` inside of the formatted_duration function is not being recognized.

2024-10-02 18:59 UTC, carmichaelong commented
Thanks for checking that. Makes sense that it didn't work. I pushed a change because the field name is `processed_duration` (rather than just `duration`).

2024-10-02 23:03 UTC, AlbertoCasasOrtiz commented
It was failing now, but just found what the problem was. Since processed duration can be null or blank, it could not access to the total_seconds() for a non-defined object.

I just added an if-else (I returned the object as is without formatting in the case it is undefined, so check if that is what we want).

2024-10-02 23:39 UTC, carmichaelong commented
Awesome, yes, that's the formatting that I was going for! LGTM.

2024-10-02 23:54 UTC, AlbertoCasasOrtiz approved these changes
Everything LGTM after the changes, approving!

2024-10-03 20:25 UTC, merged